parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: next
  sourceType: module

extends:
  - prettier
  - plugin:@typescript-eslint/recommended

plugins:
  - svelte3
  - '@typescript-eslint/'

overrides:
  - files: '*.svelte'
    processor: svelte3/svelte3

settings:
  svelte3/typescript: true

env:
  es6: true
  node: true
  browser: true
